export const SHOW_MESSAGE = 'SHOW_MESSAGE'
export const SET_MESSAGE = 'SET_MESSAGE'

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const AUTHENTICATE = 'AUTHENTICATE'
export const ACCESS_TOKEN = 'ACCESS_TOKEN'

export const SET_PRELOAD_DATA = 'SET_PRELOAD_DATA'

export const SET_KEYWORD = 'SET_KEYWORD'
export const SET_SELECTED_SERVICE = 'SET_SELECTED_SERVICE'
export const SET_SELECTED_AREA = 'SET_SELECTED_AREA'
