export const SHOW_MESSAGE = 'SHOW_MESSAGE'
export const SET_MESSAGE = 'SET_MESSAGE'

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const AUTHENTICATE = 'AUTHENTICATE'
export const ACCESS_TOKEN = 'ACCESS_TOKEN'

export const SET_PRELOAD_DATA = 'SET_PRELOAD_DATA'

export const SET_KEYWORD = 'SET_KEYWORD'
export const SET_LOCATION = 'SET_LOCATION'
export const SET_POSITION = 'SET_POSITION'
export const SET_SELECTED_SERVICE = 'SET_SELECTED_SERVICE'
export const SET_SELECTED_AREA = 'SET_SELECTED_AREA'
export const SET_SELECTED_CITY = 'SET_SELECTED_CITY'
export const ADD_FILTER = 'ADD_FILTER'
export const REMOVE_FILTER = 'REMOVE_FILTER'

export const ADD_SERVICE_TO_CART = 'ADD_SERVICE_TO_CART'
export const REMOVE_SERVICE_FROM_CART = 'REMOVE_SERVICE_FROM_CART'
export const SET_SALON_TO_CART = 'SET_SALON_TO_CART'
export const SET_STYLIST_TO_CART = 'SET_STYLIST_TO_CART'
export const SET_BOOKING_DATE = 'SET_BOOKING_DATE'
export const APPLY_PROMO_CODE = 'APPLY_PROMO_CODE'
export const REMOVE_PROMO_CODE = 'REMOVE_PROMO_CODE'
export const CLEAR_CART = 'CLEAR_CART'

export const SET_YOUR_LOCATION = 'SET_YOUR_LOCATION'
