export default (http, store, router) => {
  // https://github.com/mzabriskie/axios#interceptors
  http.interceptors.response.use(
    response => response,
    /**
    * This is a central point to handle all
    * error messages generated by HTTP
    * requests
    */
    (error) => {
      const { response } = error

      // if ([401].indexOf(response.status) > -1) {
      //   store.dispatch('logout').then(() => router.push({ name: 'login' }))
      // }

      store.dispatch('setError', response.data)

      return Promise.reject(error)
    }
  )
}
